apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: workshop
nameSuffix: -prod

resources:
 - backend/deployment.yaml
 - backend/service.yaml
 - frontend/deployment.yaml
 - frontend/service.yaml

images:
  - name: <AWS_ACCOUNT_NUMBER>.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
    newName: <AWS_ACCOUNT_NUMBER>.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
    newTag: v1.0

  - name: <AWS_ACCOUNT_NUMBER>.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
    newName: <AWS_ACCOUNT_NUMBER>.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
    newTag: v1.0